### PR TITLE
[175108106] Integrate ES6+

### PR DESCRIPTION
**Pull request by developerbello**
## Description

[175108106](https://www.pivotaltracker.com/n/projects/2468739/stories/175108106)

• Changed the babel setup file as `babel.config.json`
• Added 3 babel package based on their use
• Added all package as development dependencies

## Additional Change

### CODE REVIEW

**Comment by abdulfataiaka** [comment]
The ESLint configuration should be on the whole project and not individual workspace

**Review by abdulfataiaka — CHANGES_REQUESTED** [review]
Dropped a comment

**Comment by developerbello** [comment]
@abdulfataiaka These PR is basically on Integrating ES6+ with babel, which added the configuration for babel, So I don't understand what you are trying to express from the above comment. And ESLint was assigned @yuusuf4real

**Comment by abdulfataiaka** [comment]
Sorry I meant your babel configuration not ESLint

**Review by abdulfataiaka — APPROVED** [review]

**Pull request merged**
